// AUTHENTICATION
// SIGN UP
export const AUTH_SIGNUP_START = "AUTH_SIGNUP_START";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_ERROR = "AUTH_SIGNUP_ERROR";

// LOG IN
export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

// FRIENDS
// GET FRIENDS
export const GET_FRIENDS_START = "GET_FRIENDS_START";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_ERROR = "GET_FRIENDS_ERROR";

// SEARCH
export const SEARCH_FRIENDS_START = "SEARCH_FRIENDS_START";
export const SEARCH_FRIENDS_SUCCESS = "SEARCH_FRIENDS_SUCCESS";
export const SEARCH_FRIENDS_ERROR = "SEARCH_FRIENDS_ERROR";

// SEND FRIEND REQUEST
export const ADD_FRIEND_START = "ADD_FRIEND_START";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_ERROR = "ADD_FRIEND_ERROR";

// ACCEPT FRIEND REQUEST
export const ACCEPT_FRIEND_START = "ACCEPT_FRIEND_START";
export const ACCEPT_FRIEND_SUCCESS = "ACCEPT_FRIEND_SUCCESS";
export const ACCEPT_FRIEND_ERROR = "ACCEPT_FRIEND_ERROR";

// REJECT FRIEND REQUEST
export const REJECT_FRIEND_START = "REJECT_FRIEND_START";
export const REJECT_FRIEND_SUCCESS = "REJECT_FRIEND_SUCCESS";
export const REJECT_FRIEND_ERROR = "REJECT_FRIEND_ERROR";

// GET FRIENDS REQUEST
export const GET_FRIEND_REQUESTS_START = "GET_FRIEND_REQUESTS_START";
export const GET_FRIEND_REQUESTS_SUCCESS = "GET_FRIEND_REQUESTS_SUCCESS";
export const GET_FRIEND_REQUESTS_ERROR = "GET_FRIEND_REQUESTS_ERROR";
